model: resnet101_attention
outputpath: experiments/resnet101_attention

dataset_base_path: /home/TuYuqing/A-Practical-Course-to-Intelligent-Perception-and-Cognition/Project3/data/flickr8k
vocab_path: utils/vocab_set.pkl

decoder_size: 512
embedding_dim: 256
attention_dim: 256
sample_method: beam # 'greed' or 'beam'
train_args:
    batch_size: 128
    learning_rate: !!float 1e-3
    num_epochs: 45
    save_freq: 10
    sample_method: sigmoid
eval_args:
    batch_size: 1

